export const INITIALIZE_ROUTINES_SUCCESS = 'INITIALIZE_ROUTINES_SUCCESS';
export const SET_NEW_ROUTINE_DAY = 'SET_NEW_ROUTINE_DAY';
export const SET_NEW_ROUTINE_START = 'SET_NEW_ROUTINE_START';
export const SET_NEW_ROUTINE_END = 'SET_NEW_ROUTINE_END';
export const SET_NEW_ROUTINE_DESCRIPTION = 'SET_NEW_ROUTINE_DESCRIPTION';
